"""Render and install the ``~/.slicerrc.py`` bootstrap.

The rc file is deliberately minimal: it only puts the package on ``sys.path``
and calls :func:`slicer_presets.install`. Slicer executes the rc file with
``exec(..., globals())`` in its main Python context, so every name is prefixed
with an underscore to keep the interactive namespace clean.
"""

from __future__ import annotations

import os
import time
from pathlib import Path

MARKER = "# generated by slicer-presets install-rc"

TEMPLATE = '''# ~/.slicerrc.py
{marker} (v{version}) - re-run "slicer-presets install-rc" instead of editing.
# All logic lives in the slicer_presets package; override its location with
# the SLICER_PRESETS_HOME environment variable, the spec file with
# SLICER_PRESETS_SPEC and the preset with SLICER_PRESET.
import logging as _logging
import os as _os
import sys as _sys

_home = _os.environ.get("SLICER_PRESETS_HOME", {home!r})
try:
    if _home not in _sys.path:
        _sys.path.insert(0, _home)
    import slicer_presets as _slicer_presets

    _slicer_presets.install()
except Exception:  # a preset problem must never break Slicer startup
    _logging.getLogger("slicer_presets").exception(
        "startup hook failed; Slicer continues without segment presets"
    )
'''


def render(home: str | os.PathLike[str]) -> str:
    from . import __version__

    return TEMPLATE.format(marker=MARKER, version=__version__, home=str(Path(home)))


def rc_path() -> Path:
    """Where Slicer looks for the user rc file (``$SLICERRC`` or ``~/.slicerrc.py``)."""
    env = os.environ.get("SLICERRC")
    return Path(env) if env else Path.home() / ".slicerrc.py"


def is_generated(text: str) -> bool:
    return MARKER in text


def install_rc(home: str | os.PathLike[str], path: str | os.PathLike[str] | None = None, *, force: bool = False) -> tuple[Path, Path | None]:
    """Write the bootstrap. Returns ``(rc_path, backup_path_or_None)``.

    An existing hand-written rc file is refused unless ``force`` is set; a file
    written by this tool is replaced silently. Any replaced file is backed up.
    """
    target = Path(path) if path else rc_path()
    backup: Path | None = None
    if target.exists():
        existing = target.read_text(encoding="utf-8", errors="replace")
        if not is_generated(existing) and not force:
            raise FileExistsError(f"{target} exists and was not generated by slicer-presets; use --force to replace it (a backup is kept)")
        backup = target.with_name(target.name + ".bak-" + time.strftime("%Y%m%d-%H%M%S"))
        backup.write_text(existing, encoding="utf-8")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render(home), encoding="utf-8")
    return target, backup
